### ISSUE TITLE
Running the contributed command:'extension.iis-express.start' failed.

### ISSUE THREAD

**Issue by Spragalas** [warrenbuckley/IIS-Express-Code#39]
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
--
Windows 10
--
Happens after latest vscode update. You can start iis-express first time and then close it. But after it just wont start.

**Comment by gaspardip** [comment]
Same here, you have to restart vscode in order to start the website again

**Comment by josephliccini** [comment]
Same here

**Comment by warrenbuckley** [comment]
Sorry for the delay all, day job & life been getting in the way!
Hope to look at this & figure out whats going on soon, least its now on my radar.

**Comment by warrenbuckley** [comment]
Hi all,
Is it possible to give me a list of extensions that you have installed please
@Spragalas @gaspardip @swensorm @josephliccini 

Thanks,
Warrem

**Comment by gaspardip** [comment]
Quite a few actually.

* Apache Conf
* Auto Close Tag
* Beautify
* C/C++
* C#
* Debugger for Chrome
* Discord Presence
* EditorConfig for VS Code
* ESLint
* Git History
* Guides
* IIS Express
* mssql
* Node Debug 2
* npm
* npm Intellisense
* PHP Debug
* PHP Intellisense
* Python
* React Native Tools
* Sass
* TSLint
* Vetur
* vscode-icons

**Comment by warrenbuckley** [comment]
OK it's weird indeed, my development copy of this when I debug & test this works fine without problem which spins up a test/dev instance of VS Code with the extension installed in it, however I have the same version installed from the VS Code Gallery & I get the exact same error as you all do in my day to day instance.

So with me unable to reproduce it with the debugger & the VS code instance makes it hard for me to find out the cause, however the joys of goggle has listed some other repo's with the same error of 
```
Error: Channel has been closed
```

https://github.com/Microsoft/vscode-jshint/issues/60
https://github.com/JakeBecker/vscode-elixir-ls/issues/73
https://github.com/redhat-developer/vscode-java/issues/533

So with a few extensions having the same reported problem, I am curious if its a wider issue & raised an issue on the main VSCode tracker to see if this is the case or not, if you want to follow along - https://github.com/Microsoft/vscode/issues/50955

**Comment by warrenbuckley** [comment]
OK @Spragalas @gaspardip @swensorm @josephliccini @avieru 
I may have a fix and would be interested if you can test out the attached .VISX file and then use VS Code to install from the local file with `Extensions: Install from VISX` from the command pallete

If it does then I can get a patch out early next week then
[UnZipMe-IIS-Express-Local-Test.zip](https://github.com/warrenbuckley/IIS-Express-Code/files/2065311/UnZipMe-IIS-Express-Local-Test.zip)

**Comment by mattchanner** [comment]
@warrenbuckley I ran into the same problem and your attached zip file fixed it for me

**Comment by warrenbuckley** [comment]
I have published 1.1.1 just now which should fix this issue - however I am not sure why or how it was caused by VS Code and still curious.

Will close this for now, but if it does not work for all or if it comes back after updating to 1.1.1 then let's re-open this issue & get to the bottom of it.

**Comment by swensorm** [comment]
Finally got a chance to test the update 1.1.1.  It's not perfect, but a vast improvement, thank you!  I still received an error when I do `>IIS Express: Restart Website` multiple times.  IIS Express is shut down, but just doesn't start back up.  It does start up if I do `>IIS Express: Start Website` again and I don't have to reload VS Code so not too annoying.  Thanks again!

```
[2018-06-06 14:07:54.393] [exthost1] [error] Error: Channel has been closed
	at e.validate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:591)
	at e.clear (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:291)
	at IIS.stopWebsite (C:\Users\ryanswenson\.vscode\extensions\warren-buckley.iis-express-1.1.1\out\IISExpress.js:125:22)
	at IIS.restartSite (C:\Users\ryanswenson\.vscode\extensions\warren-buckley.iis-express-1.1.1\out\IISExpress.js:158:18)
	at vscode.commands.registerCommand (C:\Users\ryanswenson\.vscode\extensions\warren-buckley.iis-express-1.1.1\out\extension.js:66:17)
	at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:704)
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:141)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:737)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:455)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:529)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:298)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:226
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:324
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20) extension.iis-express.restart
```

**Comment by swensorm** [comment]
Looking closer at the code in stopWebsite `this._output` is cleared, hidden, and disposed of, but never set to null/undefined.  In startWebsite it's used again:
```js
this._output = this._output || vscode.window.createOutputChannel('IIS Express');
```
I'm a bit surprised it doesn't error every time it's stopped/started.

I modified the `out\IISExpress.js` file to set `this._output = null;` after dispose and I didn't receive the error again after several restarts.  I removed it again, just to verify, and received the error on my 2nd `Restart Website`.

**Comment by warrenbuckley** [comment]
@swensorm thanks for the eagle eye catch there & fix, I will look tomorrow when I am back at my desk again.

Sorry for the mess up, but at least it's slowly getting better 😛 
Happy to take any PR's or improvements as it was mostly done from a POC

**Comment by swensorm** [comment]
No worries, glad I could help, a little.  Definitely a useful extension for all of us here.  Makes working in Sitefinity (monolith CMS) almost tolerable 😉
